No change history kept

diff --git a/pl_makesd b/pl_makesd
--- a/pl_makesd
+++ b/pl_makesd
@@ -5,6 +5,43 @@
 # wiped out!
 SD=/dev/sdb
 
+# Make sure we're running via sudo
+if [ $(id -u) -ne 0 ]; then
+    sudo $0 $1 $2 $3 $4 $5
+    exit
+fi
+
+
+update_boot_partition()
+{
+    #
+    # Mount the first paritition and copy the boot files
+    #
+    echo "Copying boot files to ${SD}1..."
+    dst=/media/sd1
+    mkdir -p     $dst
+    mount ${SD}1 $dst
+    cp $src/BOOT.BIN $dst
+    cp $src/boot.scr $dst
+    cp $src/image.ub $dst
+
+    # We're done
+    umount ${SD}1
+}
+
+
+# Check to see if the user only wants to update the boot partition
+update_only=0;
+if [ "$1" == "-update" ] || [ "$1" == "--update" ]; then
+    shift
+    update_only=1
+fi
+
+# Check for unrecognized command parameters
+if [ ! -z $1 ]; then
+    echo "Unrecognized parameters on command line" 1>&2
+    exit 1
+fi
 
 #
 #  Check to see if the SD card exists
@@ -14,18 +51,31 @@ if [ ! -b $SD ]; then
     exit 1
 fi
 
-if [ $(id -u) -ne 0 ]; then
-    sudo $0 $1 $2 $3 $4 $5
-    exit
+
+#
+#  Figure out where the boot files are
+#
+if [ -f images/linux/BOOT.BIN ]; then 
+    src=images/linux
+elif [ -f linux/images/BOOT.BIN ]; then
+    src=linux/images
+else
+    echo "BOOT.BIN not found!"
+    exit 1
 fi
-
-
 
 #
 # Ensure that there are no SD cards mounted
 #
 umount /dev/sd* 2>/dev/null
 
+
+# If we're just updating the boot partition, make it so
+if [ $update_only -eq 1 ]; then
+    update_boot_partition
+    echo "Boot partition updated"
+    exit 0
+fi
 
 # Tell the user what we're up to
 echo "Erasing $SD..."
@@ -72,50 +122,29 @@ EOT
 echo "Creating FAT file-system..."
 mkfs.fat ${SD}1 >/dev/null
 
-
 #
 # Create the EXT4 Linux filesystem
 #
 echo "Creating EXT4 file-system..."
 mkfs.ext4 ${SD}2 >/dev/null 2>/dev/null
 
-
-#
-#  Figure out where the boot files are
-#
-if [ -f images/linux/BOOT.BIN ]; then 
-    src=images/linux
-elif [ -f linux/images/BOOT.BIN ]; then
-    src=linux/images
-else
-    echo "BOOT.BIN not found!"
-    exit 1
-fi
-
-#
-# Mount the first paritition and copy the boot files
-#
-echo "Copying boot files to ${SD}1..."
-dst=/media/sd1
-mkdir -p     $dst
-mount ${SD}1 $dst
-cp $src/BOOT.BIN $dst
-cp $src/boot.scr $dst
-cp $src/image.ub $dst
+# Copy our files to the boot partition
+update_boot_partition
 
 #
 # Mount the second partition and copy the root filesystem
 #
-echo "Copying rootfs to ${SD}2..."
-dst=/media/sd2
-mkdir -p     $dst
-mount ${SD}2 $dst
-tarball=$(realpath $src/rootfs.tar.gz)
-cd $dst
+#echo "Copying rootfs to ${SD}2..."
+#dst=/media/sd2
+#mkdir -p     $dst
+#mount ${SD}2 $dst
+#tarball=$(realpath $src/rootfs.tar.gz)
+#cd $dst
 #sudo tar -xzf $tarball
-sync;sync;
-cd - >/dev/null
+#sync;sync;
+#cd - >/dev/null
+# umount ${SD}2
+
 
 # We're done!
-umount ${SD}1 ${SD}2
 echo "SD create complete"
